---
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    carto.run/workload-name: petclinic
spec:
  containers:
    - name: web
      image: ubuntu
      args:
        - /bin/sh
        - -c
        - >
          while true;
          do
            date
            sleep 1
          done
